### ISSUE TITLE
Warning on console after reorder

### ISSUE THREAD

**Issue by OuSS-90** [markedwardmurray/SQReorderableStackView#1]
Hello, thanks for this awesome library,
I have small issue, I'm getting this warning "<CATransformLayer: 0x1450cf050> - changing property masksToBounds in transform-only layer, will have no effect every time I reorder stackViews"
Thanks,

**Comment by markedwardmurray** [comment]
Thanks for reporting. It looks like the corner radius animation stopped working at some point, possibly related to iOS 11 changes to UIKit. I've simply removed the feature to silence the console. Cheers!
